version: '{build}'
image: Visual Studio 2017
branches:
  only:
    - master
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
init:
- ps: |
    .\scripts\make_init.ps1
    .\scripts\make_debug_rdp.ps1
build_script:
- ps: |
    .\scripts\make_build.ps1
test_script:
- ps: |
    .\scripts\make_test.ps1

artifacts:
  - path: 'release\*.msi'
    name: MsiInstallers

environment:
  mattermost_build_date:

deploy:
  # Nightly build
  - provider: GitHub
    auth_token:
      secure: tf2cb9v2kDuXUd6G9jjrwXHCVXCcYk72BzpVhxLQssov6uLGiBlIRCvi4Wd0MWCV
    release: $(APPVEYOR_BUILD_NUMBER) ($(APPVEYOR_REPO_COMMIT)) (via AppVeyor)
    description: 'Dev version'
    artifact: MsiInstallers
    prerelease: true
    force_update: true
    on:
      branch: master
  # Taggued releases
  - provider: GitHub
    auth_token:
      secure: tf2cb9v2kDuXUd6G9jjrwXHCVXCcYk72BzpVhxLQssov6uLGiBlIRCvi4Wd0MWCV
    release: $(APPVEYOR_REPO_TAG_NAME) ($(MATTERMOST_BUILD_DATE)) (via AppVeyor)
    description: 'Release'
    artifact: MsiInstallers
    draft: true
    force_update: false
    on:
      APPVEYOR_REPO_TAG: true

on_finish:
- ps: