version: '{build}'
image: Visual Studio 2017
branches:
  only:
    - master
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

init:
  # Do not try to run a Powershell script from the repo here, because at this
  # stage (init) the repo is not cloned yet.

build_script:
- ps: |
    .\scripts\make_debug_rdp.ps1
    .\scripts\make_build.ps1

test_script:
- ps: |
    .\scripts\make_test.ps1

# Secure variables are not decoded during Pull Request
# src.: https://www.appveyor.com/docs/build-configuration/#secure-variables
environment:
  encrypted_cert_private_key:
    secure: kP+bhs38HreY0NCCl2t6QwGsxILhAKuzHmuSCriwP1g=

artifacts:
  - path: 'release\*.msi'
    name: MsiInstallers

deploy:
  # Nightly build
  - provider: GitHub
    auth_token:
      secure: I2wx9gajpvBjcxtEKYoYqqmyoH/2fWQflycpwlHZY9SD9sFkPlA4CNMcF29dcI4j
    release: $(APPVEYOR_BUILD_NUMBER) ($(APPVEYOR_REPO_COMMIT)) (via AppVeyor)
    description: 'Dev version'
    artifact: MsiInstallers
    prerelease: true
    force_update: true
    on:
      branch: master
  # Taggued releases
  - provider: GitHub
    auth_token:
      secure: I2wx9gajpvBjcxtEKYoYqqmyoH/2fWQflycpwlHZY9SD9sFkPlA4CNMcF29dcI4j
    release: $(APPVEYOR_REPO_TAG_NAME) ($(MATTERMOST_BUILD_DATE)) (via AppVeyor)
    description: 'Release'
    artifact: MsiInstallers
    draft: true
    force_update: false
    # Update the existing tag rather than creating a new one
    tag: $(APPVEYOR_REPO_TAG_NAME)
    on:
      APPVEYOR_REPO_TAG: true

on_finish:
- ps: |
    # Some Powershell script to run at the end